name: KUDO Release Automation
on:
  push:
    tags:
     - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Code
       uses: actions/checkout@v1
     - name: Login to DockerHub Registry
       run: docker login -u farhan5900 -p FarHan59oo
     - name: Download and Install Go
       run: |
         sudo snap install --classic --channel=1.16/stable go
     - name: Download and Extract GoReleaser
       run: |
         curl -Ls https://github.com/goreleaser/goreleaser/releases/download/v0.164.0/goreleaser_Linux_x86_64.tar.gz | tar -xzf - -C /tmp
     - name: Run the Release
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         /tmp/goreleaser --rm-dist
