name: KUDO Release Automation
on:
  push:
    tags:
     - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Code
       uses: actions/checkout@v1
     - name: Download GoReleaser
       run: |
         curl -LO https://github.com/goreleaser/goreleaser/releases/download/v0.164.0/goreleaser_Linux_x86_64.tar.gz
     - name: Extract GoReleaser Binary
       run: |
          mkdir -p goreleaser && tar -xzf goreleaser_Linux_x86_64.tar.gz --directory ./goreleaser
     - name: Run the Release
       run: |
         ./goreleaser/goreleaser --rm-dist
